# Generated by Django 3.2.2 on 2021-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer_id', models.TextField(max_length=20)),
                ('lat', models.FloatField(max_length=25)),
                ('lang', models.FloatField(max_length=25)),
                ('name_location', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('help', models.TextField(max_length=255)),
                ('area', models.TextField(max_length=20)),
            ],
        ),
    ]
