# Generated by Django 3.2.2 on 2021-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_form_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='answer',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
