# Generated by Django 3.2.2 on 2021-05-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_form_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='lang',
            new_name='long',
        ),
    ]
