# Generated by Django 3.2.2 on 2021-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210726_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
