# Generated by Django 3.2.2 on 2021-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_form_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.TextField(db_index=True, max_length=25)),
                ('team_name', models.TextField(db_index=True, max_length=25)),
                ('players', models.IntegerField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
