# Generated by Django 3.2.2 on 2021-10-30 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20211030_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
