# Generated by Django 3.2.2 on 2021-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='game_code',
            field=models.TextField(db_index=True, default=' ', max_length=25),
            preserve_default=False,
        ),
    ]
